In [1]:
import pandas as pd
import numpy as np

## Original DataFrame

In [2]:
og_data = pd.read_csv("clean_dataset_2(6nov19).csv")

In [3]:
og_data.shape

(424431, 30)

In [4]:
og_data.head()

,Vehicle_Symbol,Vehicle_Make_Year,Vehicle_Collision_Coverage_Deductible,Vehicle_Performance_High,Vehicle_Performance_Intermediate,Vehicle_Anti_Theft_Device_Alarm Only,Vehicle_Anti_Theft_Device_Passive Disabling-Vehicle Recovery,Vehicle_Passive_restraint_Y,Policy_Installment_Term,Vehicle_Med_Pay_Limit,...,Vehicle_Youthful_Good_Student_Code_Eligible for Good Student Credit,Vehicle_Driver_Points,Policy_CompanyY,EEA_Multi_Auto_Policies_IndicatorY,EEA_Liability_Coverage_Only_IndicatorY,EEA_Agency_TypeY,EEA_Packaged_Policy_IndicatorY,EEA_Full_Coverage_IndicatorY,Annual_Premium,Loss_Amount
0,11,2004,500,0,0,0,0,1,6,1000,...,0,0,1,1,1,1,1,1,320.12,0.0
1,11,1980,50,0,0,0,0,0,6,2000,...,0,0,0,0,0,0,0,0,259.70,0.0
2,10,2005,100,0,0,0,1,1,6,50000,...,0,0,1,1,1,1,1,1,613.74,0.0
3,12,2005,250,0,0,0,1,1,6,5000,...,0,0,1,1,1,1,1,1,541.66,0.0
4,12,2005,250,0,0,0,1,1,6,5000,...,0,0,1,1,1,1,1,1,541.66,0.0

In [5]:
updated_data = og_data[og_data['Loss_Amount'] > 0]

In [6]:
updated_data.shape

(18869, 30)

In [7]:
og_data = og_data[og_data['Loss_Amount'] == 0]

In [8]:
og_data.shape

(405562, 30)

## Dividing Original Dataframe into chunks of 500

In [9]:
max_rows = 478
m = 22
chunked_dataframes = []
while len(og_data) > max_rows:
    top = og_data[:max_rows]
    top = top.append(updated_data[:m])
    chunked_dataframes.append(top)
    og_data = og_data[max_rows:]
    updated_data = updated_data[m:]
else:
    top = (og_data)
    top = top.append(updated_data)
    chunked_dataframes.append(top)

## List of Dataframes

In [10]:
len(chunked_dataframes)

849

In [11]:
first_dataframe = chunked_dataframes[0]

In [12]:
first_dataframe.shape

(500, 30)

## Function to Compress Dataframe of 500 rows into one row and making a new dataframe of one row

In [13]:
def compress_dataFrame(first):
    for row in first:
        first[row] = first[row].mean()
    first_new = first[:1]
    return first_new

## Appending Dataframes of one row each into a list of Dataframes

In [14]:
merged_dataframes = []
for dataframe in chunked_dataframes:
    merged_dataframes.append(compress_dataFrame(dataframe))

In [15]:
len(merged_dataframes)

849

## Merging the list of 849 dataframes into one final dataframe

In [16]:
final_dataframe = pd.concat([df for df in merged_dataframes])

## Final Dataframe compressing data from 5 million rows to 850 rows

In [17]:
final_dataframe.shape

(849, 30)

In [18]:
final_dataframe.head(10)

,Vehicle_Symbol,Vehicle_Make_Year,Vehicle_Collision_Coverage_Deductible,Vehicle_Performance_High,Vehicle_Performance_Intermediate,Vehicle_Anti_Theft_Device_Alarm Only,Vehicle_Anti_Theft_Device_Passive Disabling-Vehicle Recovery,Vehicle_Passive_restraint_Y,Policy_Installment_Term,Vehicle_Med_Pay_Limit,...,Vehicle_Youthful_Good_Student_Code_Eligible for Good Student Credit,Vehicle_Driver_Points,Policy_CompanyY,EEA_Multi_Auto_Policies_IndicatorY,EEA_Liability_Coverage_Only_IndicatorY,EEA_Agency_TypeY,EEA_Packaged_Policy_IndicatorY,EEA_Full_Coverage_IndicatorY,Annual_Premium,Loss_Amount
0,10.026,1995.700,264.974,0.006,0.024,0.058,0.254,0.590,6.132,2979.950,...,0.008,0.062,0.590,0.590,0.590,0.590,0.590,0.590,312.47698,217.20920
495,10.016,1995.504,242.412,0.004,0.020,0.056,0.240,0.620,6.084,2997.888,...,0.018,0.084,0.620,0.620,0.620,0.620,0.620,0.620,300.96818,67.02510
993,9.644,1995.330,258.630,0.002,0.020,0.060,0.254,0.600,6.084,3137.930,...,0.004,0.072,0.600,0.600,0.600,0.600,0.600,0.600,303.37060,178.84100
1488,10.578,1995.828,250.956,0.012,0.030,0.066,0.256,0.664,6.216,3051.890,...,0.014,0.112,0.664,0.664,0.664,0.664,0.664,0.664,334.66896,90.71088
1978,10.554,1996.218,256.118,0.012,0.022,0.068,0.268,0.662,6.228,3121.904,...,0.012,0.068,0.662,0.662,0.662,0.662,0.662,0.662,323.49508,95.97946
2473,10.324,1996.390,276.464,0.006,0.026,0.066,0.278,0.680,6.180,2921.916,...,0.000,0.076,0.680,0.680,0.680,0.680,0.680,0.680,316.64934,54.02238
2976,10.378,1996.482,284.496,0.008,0.024,0.070,0.268,0.672,6.156,3053.936,...,0.008,0.092,0.672,0.672,0.672,0.672,0.672,0.672,334.28182,118.34456
3471,10.164,1995.934,267.252,0.002,0.010,0.060,0.274,0.660,6.132,2713.918,...,0.010,0.070,0.660,0.660,0.660,0.660,0.660,0.660,308.60068,66.21032
3964,10.120,1995.564,260.524,0.006,0.016,0.062,0.262,0.610,6.120,4253.916,...,0.010,0.090,0.610,0.610,0.610,0.610,0.610,0.610,305.45610,172.56200
4453,10.340,1996.046,277.262,0.014,0.020,0.050,0.270,0.626,6.192,3613.922,...,0.004,0.064,0.626,0.626,0.626,0.626,0.626,0.626,320.17728,166.66382